// <auto-generated />
using System;
using MachineSimulation.DataAccess.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachineSimulation.DataAccess.Migrations
{
    [DbContext(typeof(MachineSimulationContext))]
    [Migration("20240418091500_seedData_3")]
    partial class seedData_3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("MachineSimulation.Entities.Concrete.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModbusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "PlastikEnjeksiyon.jpg",
                            MachineName = "Plastik Enjeksiyon",
                            MachineType = "enjeksiyon",
                            ModbusId = 4096,
                            ProductionCount = 0
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "KitamuraCncTezgahı.jpg",
                            MachineName = "Kitamura Cnc Tezgahı",
                            MachineType = "cnc",
                            ModbusId = 4097,
                            ProductionCount = 0
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "AbkantPress.jpg",
                            MachineName = "Abkant Press",
                            MachineType = "press",
                            ModbusId = 4098,
                            ProductionCount = 0
                        });
                });

            modelBuilder.Entity("MachineSimulation.Entities.Concrete.MachineLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MachineLogs");
                });

            modelBuilder.Entity("MachineSimulation.Entities.Concrete.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Event")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModbusIp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Event = 1,
                            MachineId = 1,
                            ModbusIp = 2249,
                            OperationName = "Hazırlık Başlat"
                        },
                        new
                        {
                            Id = 2,
                            Event = 2,
                            MachineId = 1,
                            ModbusIp = 2249,
                            OperationName = "Hazırlık Bitir"
                        },
                        new
                        {
                            Id = 3,
                            Event = 3,
                            MachineId = 1,
                            ModbusIp = 2255,
                            OperationName = "Üretim Başlat"
                        },
                        new
                        {
                            Id = 4,
                            Event = 4,
                            MachineId = 1,
                            ModbusIp = 2255,
                            OperationName = "Üretim Bitir"
                        },
                        new
                        {
                            Id = 5,
                            Event = 1,
                            MachineId = 2,
                            ModbusIp = 2250,
                            OperationName = "Hazırlık Başlat"
                        },
                        new
                        {
                            Id = 6,
                            Event = 2,
                            MachineId = 2,
                            ModbusIp = 2250,
                            OperationName = "Hazırlık Bitir"
                        },
                        new
                        {
                            Id = 7,
                            Event = 3,
                            MachineId = 2,
                            ModbusIp = 2256,
                            OperationName = "Üretim Başlat"
                        },
                        new
                        {
                            Id = 8,
                            Event = 4,
                            MachineId = 2,
                            ModbusIp = 2256,
                            OperationName = "Üretim Bitir"
                        },
                        new
                        {
                            Id = 9,
                            Event = 1,
                            MachineId = 3,
                            ModbusIp = 2251,
                            OperationName = "Hazırlık Başlat"
                        },
                        new
                        {
                            Id = 10,
                            Event = 2,
                            MachineId = 3,
                            ModbusIp = 2251,
                            OperationName = "Hazırlık Bitir"
                        },
                        new
                        {
                            Id = 11,
                            Event = 3,
                            MachineId = 3,
                            ModbusIp = 2257,
                            OperationName = "Üretim Başlat"
                        },
                        new
                        {
                            Id = 12,
                            Event = 4,
                            MachineId = 3,
                            ModbusIp = 2257,
                            OperationName = "Üretim Bitir"
                        });
                });

            modelBuilder.Entity("MachineSimulation.Entities.Concrete.OperationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OperationLogs");
                });

            modelBuilder.Entity("MachineSimulation.Entities.Concrete.OperationParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParameterValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("ParameterId");

                    b.ToTable("OperationParameters");
                });

            modelBuilder.Entity("MachineSimulation.Entities.Concrete.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MachineId = 1,
                            ParameterName = "Hız",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 2,
                            MachineId = 1,
                            ParameterName = "Sıcaklık",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 3,
                            MachineId = 2,
                            ParameterName = "Hız",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 4,
                            MachineId = 2,
                            ParameterName = "Sıcaklık",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 5,
                            MachineId = 3,
                            ParameterName = "Cnc Ilerleme Hizi",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 6,
                            MachineId = 3,
                            ParameterName = "Ariza Alarm Sayisi",
                            ValueType = "int"
                        });
                });

            modelBuilder.Entity("MachineSimulation.Entities.Concrete.Operation", b =>
                {
                    b.HasOne("MachineSimulation.Entities.Concrete.Machine", "Machine")
                        .WithMany("Operations")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("MachineSimulation.Entities.Concrete.OperationParameter", b =>
                {
                    b.HasOne("MachineSimulation.Entities.Concrete.Operation", "Operation")
                        .WithMany("OperationParameters")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineSimulation.Entities.Concrete.Parameter", "Parameter")
                        .WithMany("OperationParameters")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("MachineSimulation.Entities.Concrete.Parameter", b =>
                {
                    b.HasOne("MachineSimulation.Entities.Concrete.Machine", "Machine")
                        .WithMany("Parameters")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("MachineSimulation.Entities.Concrete.Machine", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("MachineSimulation.Entities.Concrete.Operation", b =>
                {
                    b.Navigation("OperationParameters");
                });

            modelBuilder.Entity("MachineSimulation.Entities.Concrete.Parameter", b =>
                {
                    b.Navigation("OperationParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
